services:
    victoire_core.widget_cover_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Cover }

    #alias to the form
    victoire.widget.form.cover:
        class: Victoire\Widget\CoverBundle\Form\WidgetCoverType
        tags:
            - { name: form.type }
