services:
    victoire_core.widget_cover_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Cover }

    #alias to the entity
    victoire.widget.cover:
        class: Victoire\Widget\CoverBundle\Entity\WidgetCover

    #alias to the form
    victoire.widget.form.cover:
        class: Victoire\Widget\CoverBundle\Form\WidgetCoverType
        tags:
            - { name: form.type }

    #subscriber
    victoire.widget.cover.create.subscriber:
        class: Victoire\Widget\CoverBundle\EventSubscriber\CreateSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%victoire_widget_cover.default_styles%"
        tags:
            - { name: kernel.event_subscriber }